# -*- coding: utf-8 -*-
"""Untitled30.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fPCEP5DMaeY0NMzzaa2gw0CCtH0e_y69
"""

print("Hola mundo!!!")

edad = int(input("Intrduzca su edad: "))
longitud_nombre = len((input("Intrduzca su nombre: ")))

print(f"Su edad es de {edad} años")
print(f"Su nombre tiene {longitud_nombre} caracteres")